### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by cv-lab-x** [fangli333/SC-4DGS#2]
hi, thanks for your great work, is there a schedule to release the codes. Looking forward to your reply, thanks! @fangli333

**Comment by fangli333** [comment]
> hi, thanks for your great work, is there a schedule to release the codes. Looking forward to your reply, thanks! @fangli333

Hi,

Thank you for your interest in our work. As our paper is still in submission, the release of our code will depend on our paper's reviews and decisions. We will inform you once we release the official code. Thank you.
