### ISSUE TITLE
Comparison with COLMAP with motion mask

### ISSUE THREAD

**Issue by yifliu3** [fangli333/SC-4DGS#3]
Dear devs,

hi, thanks for your great work, which has inspired me a lot. Based on my understanding, the insight of this work is to extract static regions of each frame for estimating camera parameters. If so, I think COLMAP with motion mask can also achieve this goal, right? 

Besides, I'm a littile confused about the structural points in the paper, are 2D structural points just pixels? Looking forward to your reply, thanks!

**Comment by fangli333** [comment]
Hi Yifan,

Thank you for being so interested. Please refer to the experiment part in our paper. Our observations on the failure of COLMAP can also be aligned with the ones from [Robust Dynamic Radiance Field](https://arxiv.org/abs/2301.02239) accepted by CVPR 2023.

The 2D structural points are not just pixels. Instead, they are the 2D locations ranging from 0 to the height/width on each frame.

Thx

**Comment by yifliu3** [comment]
Got it. Thanks a lot for your prompt reply!
