### ISSUE TITLE
camera poses 

### ISSUE THREAD

**Issue by yuhaoliu7456** [fangli333/SC-4DGS#4]
I am wondering if your method can be used to obtain camera poses of dynamic monocular videos. Just like the Robust-dynrf.

**Comment by yuhaoliu7456** [comment]
particularly for the datasets like DAVIS

**Comment by fangli333** [comment]
> particularly for the datasets like DAVIS

What you said is the goal of our paper. RoDynRF is also one of the important baselines in our paper. Please refer to the experiment part of our paper to see visualizations on DAVIS dataset.

Thank you.
